### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by zannain** [CarlosSengo/tea-cozy#4]
**Awesome work on this mockup Carlos!** I'm really impressed that you not only added comments to the markup and styles but also using new HTML5 element tags such as `<section>` and `<main>`. Excellent work with adopting a CSS class naming schema, it is very similar to how [BEM](http://getbem.com/) works. Also good work on making the webpage more accessible by using `alt` attributes on the `<img>` tags! A few things I would recommend learning going forward once you have mastered Flexbox is CSS grids. Grids are new to CSS3 and they give the web developer more granular control over the responsiveness of a webpage. I've listed a few resources below to get you going. Keep up the **excellent work!!**

[CSS Grids Course](https://cssgrid.io/)

**Comment by CarlosSengo** [comment]
Many Thanks for your nice comments. I want to grow with learning industry standards so I can easily adapt to a professional work environment. That's why I'm starting to add comments to both markup and styles files. regarding html5 tags, it follows the same principle :). I will develop my Flexbox knowledge and for sure start to learn and apply CSS Grids. Many thanks for your help, Cheers
